name: tree_skeleton
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.3.0
  - torchvision=0.18.0
  - torchaudio=2.3.0
  - pytorch-cuda=11.8
  - pip
  - pip:
    - open3d
    - opencv-python
    - networkx[default]
    - tqdm
    - scipy
    - opt-einsum
    - geomdl
    - git+https://github.com/facebookresearch/detectron2.git